# Generated by Django 5.1.6 on 2025-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expected_at', models.DateTimeField()),
                ('printed', models.BooleanField(default=False)),
            ],
        ),
    ]
